### ISSUE TITLE
Tiketin poistaminen

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#101]
Lähettäjällä pitäisi olla mahdollisuus poistaa lähettämänsä tiketti.

Relevantti use-case on sellainen, että esimerkiksi opiskelija tuleekin kysymyksen lähettämisen jälkeen toisiin aatoksiin ja haluaa ettei kysymys päädy opettajille asti luettavaksi.

**Comment by JoniMatias** [comment]
Backend on tästä jo tehty.
