### ISSUE TITLE
Sähköposti-ilmoitukset

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#105]
Aluksi pitää selvittää, että millä tavalla edes voidaan lähetää luotettavasti sähköpostiviestejä Azuren App Servicestä.

SMTP relay palvelu?

**Comment by erkkitervoOY** [comment]
SMTP relay palveluna voisi olla ratkaisu.

Tai jokin muu ulkoinen sähköpostipalvelu.

Nodelle on ainakin seuraava kirjasto, jolla onnistuu sähköpostien lähettäminen käyttäen ulkoista sähköpostipalveluntarjoajaa:
https://nodemailer.com/about/

**Comment by JoniMatias** [comment]
Lähettää viestejä nyt.
