### ISSUE TITLE
Isompi hitbox listanäkymän kentille

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#106]
Frontissa kysymysten listanäkymässä pitäisi voida avata kysymys klikkaamalla listan koko rivin alueelta, eikä vain pienestä alueesta otsikon ympäriltä.

**Comment by nkahe** [comment]
kaikki kentät ovat nyt linkkejä. kenttien paddingit ovat myös hitboxeja, niin ne ovat isompia.
