### ISSUE TITLE
Tilakaavion muutos

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#113]
"Ratkaisu" tila ja kommenttiin laitettava "Ratkaisuehdotus" on tällä hetkellä hämmentävä. Kaikille ei ole ihan selvää heti alussa, että miten tämä toimii.

Nykyinen "Ratkaistu" tila ei toimi, jos opiskelija esimerkiksi käy kiittämässä opettajaa ratkaisuehdotuksesta.

Korjaus: Opettajille ja opiskelijoille toiminnallisuus, jolla he voivat itse asettaa tiketin tilan ratkaistuksi

Mietitään samalla koko tilakaaviota uusiksi, jos sen saisi toimimaan paremmin.

**Comment by JoniMatias** [comment]
Alustavasti päätettiin muuttaa vain sitä, miten arkistoidut tiketit näkyvät opettajalle ja opiskelijalle. 

Arkistoinnin logiikan muuttaminen kontekstisidonnaiseksi, joka lasketaan joka kerta kun /api/kurssi/:id/kaikki/ -rajapintaa kutsutaan on turhan raskas.

**Comment by JoniMatias** [comment]
Tilakaavio toimii nykyään.
