### ISSUE TITLE
Liitteiden lisääminen uuden tiketin näkymässä.

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#115]
Kun backendin liitehomma toimii ( #114 ), niin frontissa pitäisi voida lähettää liitteitä.

Tarviiko tähän tehdä taittoa etukäteen?

**Comment by nkahe** [comment]
Tällä hetkellä on perustoiminnallisuus, että pystyy lataamaan useampia liitteitä.

**Comment by nkahe** [comment]
Pystyy nyt lähettämään liitteitä.

**Comment by nkahe** [comment]
mm. yksittäisten tiedostojen uploadaamisen epäonnistumisesta voisi näyttää virheitä ja progress-barin tehdä.
