### ISSUE TITLE
[Bugi] Tiketin tila muuttuu luetuksi heti, kun opettaja avaa tikettilistan

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#118]
**Kuvaus**
Tiketin pitäisi muuttua vasta luetuksi, kun opettaja avaa yksittäisen tiketin näkymän.

**Mitä tapahtuu**
Kun opettaja avaa tikettilistan, jossa on uusi viesti, sen tilana näkyy jo luettu, vaikka sitä ei olisi luettu.

**Mitä pitäisi tapahtua**
Tiketin pitäisi olla lähetetty-tilassa.

**Miten toistaa**
Kirjaudu sisään opiskelijana
Lähetä opiskelijana tiketti opettajalle.
Kirjaudu sisään opettajana

**Veikkaus syystä**
Tämä todennäköisesti johtuu siitä, että tikettilista hakee jotain tietoa käyttäen /api/tiketti/:id -rajapintaa.

**Comment by nkahe** [comment]
En saanut toistettua tätä, vaan tiketti näkyy "Lähetetty" -tilassa. Tikettilista ei käytä /api/tiketti/:id -rajapintaa. Kaikki frontin tekemät kutsut näkyy consolessa.

**Comment by JoniMatias** [comment]
Vika oli backendin oikeuksienhallinnassa. Nyt luultavasti korjattu.
