### ISSUE TITLE
Editori: lähdekoodiblokin ottaminen pois päältä muuttaa koko blokin takaisin tekstikappaleeksi

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#124]
Sama toimii myös toisinpäin. Eli lähdekoodiblokin ottaminen pois päältä pitäisi luoda uuden rivin ja muuttaa vasta se tekstiblokiksi.

**Comment by JoniMatias** [comment]
Tämä ei ole millään tavalla relevantti, ja toimii tällä hetkellä niinkuin se olettaakin.
