### ISSUE TITLE
Editori: kuvan lisääminen editorissa aiheuttaa "Empty text nodes are not allowed" virheviestin

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#127]
Tapahtuu ainakin silloin, kun lisätään pelkkä kuva tyhjään editoriin. Kuvan lisääminen kuitenkin onnistuu, eikä sinänsä aiheuta ongelmia.

Virheviesti:
ERROR RangeError: Empty text nodes are not allowed
    TextNode index.js:1533
    text index.js:2415
    execute menu-src.component.ts:39
    update menu-src.component.ts:63
    ngOnInit menu-src.component.ts:67
    RxJS 6
    handleTransactions ngx-editor.mjs:2586
    dispatch index.js:5327
    insert ngx-editor.mjs:897
    insertLink ngx-editor.mjs:1518
    ImageComponent_div_2_Template_form_ngSubmit_1_listener ngx-editor.mjs:1533
    Angular 2
    RxJS 6
    Angular 36
    ImageComponent_div_2_Template ngx-editor.mjs:1533
    Angular 9
    ImageComponent_Template ngx-editor.mjs:171
    Angular 41
    RxJS 6
    Angular 8
core.mjs:8506:22

**Comment by JoniMatias** [comment]
Tämä ei tunnu vaikuttavan mihinkään. Ehkä tämäkin olisi silti hyvä korjata.

**Comment by JoniMatias** [comment]
Wont fix, ei vaikuta käyttöön, näkyy vain konsolissa.
