### ISSUE TITLE
Tiketin muokkausmahdollisuus fronttiin

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#131]
Tikettiä pitäisi voida muokata lähettämisen jälkeen (ks. #102 ). Backend tukee sitä jo rajapinnalla *PUT /api/tiketti/:tiketti-id/kommentti/:kommentti-id*. 

Riippuu osittain bankendin taskista #130 .

**Comment by nkahe** [comment]
Toimii muuten, mutta liitetiedostojen muokkausta ei ole vielä toteutettu.
