### ISSUE TITLE
Heti tiketin kentän lisäämisen jälkeen /kurssi/id/tiketinkentat palauttaa joskus: []

### ISSUE THREAD

**Issue by nkahe** [Digivertaisverkko/UKK-tiketit#137]

**Comment by nkahe** [comment]
Jos kenttien haku tehdään heti sen jälkeen, kun on saatu vastaus kentän lisäämisestä. fronttiin laitettu pieni viive, jolla toistaiseksi välttäisi tuon.

**Comment by JoniMatias** [comment]
Luultavasti korjattu. Nyt ainakin backend odottaa Promisen palattamista vanhojen tikettien poistosta ja uusien lisäämisestä.
