### ISSUE TITLE
Ilmoitus käyttäjälle henkilötietojen keräämisestä ennenkuin ne tallennetaan järjestelmään

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#154]

**Comment by JoniMatias** [comment]
Tämä toimii jo backendin näkökulmasta. Enää frontin pitää muuttaa hyväksy napin toiminta siihen muotoon, että se lähettää saamansa lupa-id:n takaisin backendille rajapintaan /lti/gdpr-lupa-ok/

**Comment by nkahe** [comment]
- [x] Kutsu backendille
- [x] Ohjaus listaukseen.
- [x] Käännökset
- [x] Virheilmoitus epäonnistuessa

Sisään kirjautumatta - ohjausta ja sieltä halutessa takaisin ilmoitukseen ei käytössä, kun ei kurssi ID:ä saatavilla.
