### ISSUE TITLE
Top-buttonit ja to-beginning-buttonit ovat kohdalla eri näkymissä

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#158]
Painikkeet ovat eri tasolla eri näkymissä. Kysymys kuuluukin, että onko submit näkymien tyyli oikea vai yksittäisten kysymysten näkymä? Nämä pitää saada samalle tasolle joka näkymään.

**Comment by nkahe** [comment]
vanha versio? korjasin viime viikolla. N. 20px näyttää itsellä kummassakin näkymässä, kun mittaan. Tosin asetukset -näkymissä ei (vielä) jostain syystä toimii.

**Comment by nkahe** [comment]
Pitäisi nyt toimia.
