### ISSUE TITLE
Kirjautunut käyttäjä ei pääse lukemaan toisen kurssin UKK:ita, jos ei ole kurssin osallistuja

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#161]
Jos ei ole kirjautunut sisään, niin ongelmaa ei ole.

Voi olla myös backendin bugi.

**Comment by nkahe** [comment]
Tuolloin GET-pyyntö URL:iin "http://localhost:3000/api/tiketti/65" palauttaa tilakoodi 204 ja vastaus "null".'
Sama toimii, jos on kurssin osallistuja.
