### ISSUE TITLE
Sähköposti-ilmoituksen viestin otsikon sisällön parantaminen

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#164]
Sähköposti-ilmoituksen viestin otsikossa voisi olla maininta, että mihin kurssiin kyseinen ilmoitus liittyy. Esimerkiksi kurssikoodi tai kurssin koko nimi, joka saadaan LTI:n kautta.

**Comment by JoniMatias** [comment]
Tehty
