### ISSUE TITLE
Opiskelijalle ei näytetä arkistoidut listaa

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#173]
Tällä hetkellä opiskelijoille näkyy tikettilistausnäkymässä "Näytä arkistoidut" -nappi. Uuden arkistointilogiikan mukaan sitä ei pitäisi siellä olla.

Tämän voi toteuttaa kahdella tavalla:
- Piilottaa napin roolin perusteella (opiskelijalle näytetään, opettajalle ei)
- Nappi piilotetaan sen mukaan, palauttaako /api/kurssi/:id/arkistoidut mitään.

**Comment by nkahe** [comment]
Piilotetaan opiskelijoilta
