### ISSUE TITLE
Lähetä-napit oletuksella aktiivisiksi

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#176]
Tiketin kirjoittamisessa muutetaan Lähetä-napin toiminnallisuus sellaiseksi, että se on aina painettavissa. Tarkistetaan onko tiketti lähetettävissä siinä vaiheessa, kun nappia painetaan.

 - [x] Lähetä-nappi aina aktiivinen
 - [x] Pakolliset kentät tarkistetaan lähetysnappia painettaessa
 - [x] Pakollisille kentille virhekentät lähetysnappia painettaessa (jos tarve)
 - [x] Pakollisille kentille myös tarkistus niihin tietoa syötettäessä (tarkistus siis kirjoittaessa ja lähetettäessä)

**Comment by erkkitervoOY** [comment]
Editorin validatorit #222 erillinen issue
