### ISSUE TITLE
Kurssiasetukset-sivulle parempi taitto

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#177]
Kurssiasetuksetsivu on epäselvä, joka ei kerro käyttäjälle mikä vika siinä on.

- [x] Korkean tason otsikko: Kurssiasetukset
- [x] Jonkinlainen leipäteksti, joka kertoo mitä lisäkentät ovat

**Comment by nkahe** [comment]
Testivaiheessa otsikoiden osalta
