### ISSUE TITLE
Tiketintilan kuvaukset pitää suunnitella roolikohtaisesti

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#187]
Varsinkin lähetetty-tila on opettajalle epäselvä.

Tilat:
- Lähetetty
- Käsittelyssä
- Kommentoitu
- Ratkaistu
- Lisätietoa pyydetty

**Comment by nkahe** [comment]
"Lähetetty" -tila näkyy opettajille nyt "Luettu / Unread"
