### ISSUE TITLE
Kirjautumisnappi "et ole kirjautunut" virheilmoitukseen

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#193]
Verkkosivulla, jos ei ole kirjautunut sisään, keskellä näkyy vain ilmoitus jossa lukee ettei käyttäjä ole kirjautunut sisään. Olisi näppärä, jos samassa yhteydessä olisi myös nappi, jolla käyttäjä voisi kirjautua sisään.

Tämä ei ole korkean prioriteetin korjaus, koska:
- Oletuksenä käyttäjät kirjautuvat LTI:n kautta
- Käyttäjillä ei ole edes kirjautumistunnuksia
- Jos LTI-käyttäjä tulee sähköpostin kautta tähän näkymään, mutta kirjautuminen on vanhentunut, niin kirjaudu sisään -nappi voi antaa väärän kuvan siitä, mitä käyttäjä edes voi tehdä.

**Comment by nkahe** [comment]
Pitäisi nyt tulla virheilmoitukseen, kun ollaan lupauduttu datan luovutukseen eikä olla upotuksessa. Jos ei olla lupauduttu ja ollaan upotuksessa, näytetään Luo tili-nappi.
