### ISSUE TITLE
Tiketin muokkaaminen alkuperäisillä lisäkentillä on mahdotonta

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#211]
Tiketin muokkaaminen käyttäen alkuperäisiä lisäkenttiä on tällä hetkellä mahdotonta. Tiketin muokkaaminen API-kustulla `PUT /api/tiketti/:tiketti-id/` vaatii lisäkenttien osalta seuraavat:

```
{
  otsikko: $string
  viesti: $string (ei pakollinen)
  kentat: 
  [{
    id: $int
    arvo: $string
  }]
}
```
Ongelmana tässä on se, että tikettiin asetetun alkuperäisen lisäkentän **id** on tällä hetkellä mahdotonta saada mistään ja siten on mahdotonta lähettää muokattu tiketti backendille kera kyseisen tiedon. Kun muokattavan tiketin tiedot haetaan, niin saadaan seuraavat tiedot API-kutsulla `GET /api/tiketti/:tiketti-id/kentat/`:

```
[{
  otsikko: $string 
  arvo: $string 
  tyyppi: $string
  ohje: $string
}] 
```

Tällä hetkellä frontend tekee tiketin muokkaamisen väärillä oletuksilla, eli se hakee kurssin tikettipohjan senhetkiset lisäkentät ja tällöin ainoastaan muokattavissa ovat ne kentät, jotka tiketissä oli alunperin asetettuna. Näin lisäkenttien muokkaamisen jälkeen tiketin muokkaaminen ei toimi käyttöliittymän indikoimalla tavalla.

Ratkaisuehdotus: erillinen API rajapintakutsu, jolla haetaan vastaavat tiedot, kuin API-kutsulla `GET /api/kurssi/:kurssi-id/tiketinkentat/`, mutta se palauttaisi ainoastaan tiettyyn tikettiin sidottujen kenttien tiedot. Tämä palauttaisi samalla muutakin tarpeellista tietoa muokkaamista varten, kuten _pakollinen_ ja _valinnat_.

**Comment by erkkitervoOY** [comment]
Vaatii myös muutoksia fronttiin, kun tilanne saadaan selvitettyä. Toistaiseksi front ei anna lisäkenttiä ollenkaan muokattavaksi.

**Comment by JoniMatias** [comment]
Toteutettu osana /api/tiketti/:id/kentat -rajapintaa
