### ISSUE TITLE
Datan luovutuksesta kieltäytyminen evästeeseen

### ISSUE THREAD

**Issue by nkahe** [Digivertaisverkko/UKK-tiketit#217]
Tämän pitää olla evästeessä, jota front voi lukea

**Comment by JoniMatias** [comment]
Ei laitettu evästeeksi, mutta gdpr-lupa -rajapinnan tokenid vaihdetiin hashiksi, jotta front voi tunnistaa käyttäjän aina samaksi kuin ennenkin.
