### ISSUE TITLE
Ticket-view kommentin lisääminen reactive forms komponentiksi

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#220]
Toistaiseksi editori komponenttina käytetään app-editor-legacy komponenttia. Tavoitteena on siirtyä käyttämään tämänhetkistä editoria.

Ainoa ongelma app-editor komponentissa on se, että editorin validoinnit eivät toimi oikein, eli se tarkistaa lähinnä ainoastaan sen, että onko siihen koskettu.

**Comment by nkahe** [comment]
- [ ] kommentin tekstikenttä
- [ ] liitteet (iso liitetiedosto -> invalid
