### ISSUE TITLE
Kommentti komponentin muuttaminen käyttämään reactive formsia

### ISSUE THREAD

**Issue by erkkitervoOY** [Digivertaisverkko/UKK-tiketit#221]
Toistaiseksi editori komponenttina käytetään app-editor-legacy komponenttia. Tavoitteena on siirtyä käyttämään tämänhetkistä editoria.

Ainoa ongelma app-editor komponentissa on se, että editorin validoinnit eivät toimi oikein, eli se tarkistaa lähinnä ainoastaan sen, että onko siihen koskettu.

**Comment by nkahe** [comment]
- [ ] editori
- [ ] liitetiedostot
- [ ] checkboxit toimimaan
- [ ] varmistusviesti, jos lähdetään kesken editoinnin?
