### ISSUE TITLE
Tietokannan versiontiskriptit

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#240]
Sequalize, tai jotain. Myös automaattitestausta ja muuta vastaavaa.

**Comment by JoniMatias** [comment]
Onko tämä enää korkealla prioriteetilla, kun kehitys alkaa hyytyä?

**Comment by erkkitervoOY** [comment]
Mahdollisesti sopiva moduuli tämän toteuttamiseksi: https://github.com/rickbergfalk/postgrator

**Comment by erkkitervoOY** [comment]
Toteutettu backendin postgrator branchissa.
