### ISSUE TITLE
Viestikentän "lähdekoodi" -napille parempi teksti.

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#242]
Käyttäjätestauksissa molemmat ryhmät kommentoivat lähdekoodi-napin epäselvyyttä. Asialle kannattaisi varmaan tehdä jotain, eli muuttaa tekstiä kuvaavammaksi. 

Opiskelijat ehdotti "Code snippet", mutta ehkä parempi olisi joku verbillä alkava, kuten "muotoile koodiksi".

**Comment by nkahe** [comment]
Material ikoneissa on kans code_block -ikoni jos haluaa sitä käyttää ja selite tooltipiksi. On vähän erilainen kuin koodi eli <> -ikoni.  "Muotoile koodiblokiksi" tai "koodilohkoksi" kertoisi ehkä tarkemmin, mitä tekee, mutta en tiedä, kuinka moni sen ymmärtää. Olisi hyvä, jos tekstistä/tooltipistä pystyisi jo huomaamaan, mikä ero tuolla on koodi-toiminnon kanssa (<> -ikoni).

**Comment by JoniMatias** [comment]
Poistetaan <>-ikoni (kooditägi) ja vaihdetaan "lähdekoodi"-nappi sille ikonille.

**Comment by erkkitervoOY** [comment]
Tehty yllä mainitulla tavalla.
