### ISSUE TITLE
UKK-tikettien tuonti- ja vientitoiminnon toteutus fronttiin.

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#243]
Varmaan napit kurssiasetus sivulle. 

Varmaan jotain tämmöistä (ehkä lataus ja lähetysikonien kanssa):

![Image](https://github.com/Digivertaisverkko/UKK-tiketit/assets/1462901/aa3e1b28-e9a9-4384-92ea-07b408c61613)

**Comment by nkahe** [comment]
- [ ] Napit
- [ ] Vienti
- [ ] Tuonti
- [ ] Onnistumis- ja virheilmoitukset
- [ ] Käännökset
