### ISSUE TITLE
Liitteiden koko pitäisi näyttää liitelistassa

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#252]
Tämä on jo backendissä toteutettu #199 . Rajapinnassa tämä tieto tallentuu automaattisesti liitettä lisätessä, ja palautuu kaikissa paikoissa, missä liitteiden tietoa jo lähetetään.

**Comment by nkahe** [comment]
dev-branchissa toteutettu
