### ISSUE TITLE
Tikettilistaan liiteindikaattori

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#258]
Indikaattori tikettilistaan siitä, onko tiketissä tai sen kommenteissa liitteitä.

Pitää katsella mitä hyötyä tästä on ja miten sen saa tehtyä.

**Comment by nkahe** [comment]
tooltippiä lukuunottamatta tehty

**Comment by nkahe** [comment]
tehty
