### ISSUE TITLE
Salasanan pituus tarkistetaan sisäänkirjautuessa

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#260]
Tällä hetkellä sisäänkirjautumisen käyttöliittymä tarkistaa salasanan minimipituuden. Salasanan oikeamuotoisuuden tarkistaminen ei kuulu sisäänkirjautumiseen vaan tilin luontiin, sillä oikeamuotoisuuden tarkistuksen ehdot voivat vaihtua.

Toki tällä hetkellä oikeamuotoisuudelle on vain yhden säännöt, joten tämä ei tuota ongelmia muualla kuin testauksessa.

Tietysti voidaan keskustella myös siitä, että kuuluuko salasanan muotoilua rajoittaa vai ei.

**Comment by nkahe** [comment]
ok, nyt tarkistetaan vain, että käyttäjä on kenttiin jotain kirjoittanut eli 1 merkki.
