### ISSUE TITLE
Kutsun hyväksyminen

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#262]
Kun kutsu on lähetetty käyttäjälle, tämän pitää hyväksyä kutsu. Backend olettaa tämän tapahtuvan osoitteessa (url)/join, jossa kutsu-id on url-parametrinä.

Viesti pitää lähettää hyväksymisestä osoitteseen (POST) /api/kurssi/:id/osallistujat . Kurssi-id:n saaminen voi olla frontille vaikeaa, joten tuota backendin olettamaa urlia pitänee muuttaa.

Tähän tarvitaan:
- [x] Sivu, jossa varmistetaan, että käyttäjä haluaa osallistua kurssille.
- [x] Lähettää hyväksymisen ilmoitus backendille
- [x] Ohjata käyttäjä oikealle kurssille hyväksymisen jälkeen.

Mahdollisesti voidaan keskustella siitä, pitääkö käyttäjän painaa mitään erillistä nappia käyttöliittymässä hyväksyäkseen, vai riittääkö pelkkä sähköpostilla ollut linkin painaminen.

**Comment by nkahe** [comment]
testailussa

**Comment by nkahe** [comment]
mainissa
