### ISSUE TITLE
Kutsun lähettäminen

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#263]
Kurssiasetuksen sivulle pitää laittaa toiminnallisuus, jossa opettaja voi kutsua kurssille ulkopuolisia käyttäjiä. Siinä pitää olla ainakin kutsuttavan sähköpostiosoite, ja annettava rooli.

Jos haluat näistä leiskan, niin voin tehdä jotain.

**Comment by nkahe** [comment]
on dev:ssä.
