### ISSUE TITLE
Järjestelmän aloitussivu

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#273]
Tämä on rahoittajan ehtojen kannalta hyvinkin tärkeä asia. Tällä hetkellä meillä on rahoittajan logot vain alaviitteessä sivun pohjalla, mutta rahoittaja vaatii, että "EU-lippulogon tulee olla kaikessa viestintämateriaalissa selvästi näkyvillä ja sijoitettuna huomattavalle paikalle." Yleisen tulkinnan mukaan tähän ei riitä pelkkä alaviite, koska se ei ole huomattava paikka.

Koska emme halua lippulogoa kuitenkaan joka sivulle viljellä, olisi hyvä olla aloitussivu, jossa nämä kaikki logot voisivat olla. 

Sivulla voisi olla:
- [x] Logot
- [x] Järjestelmän kuvaus
- [x] Linkki ohjeistukseen (vai onko siellä arkaluontoista tietoa)
- [x] Linkki hankkeen sivuille
- [ ] Hyviä meemejä

**Comment by nkahe** [comment]
Suunniteltavia juttuja vielä ainakin:

- Tällä hetkellä näkymään pääsee vain: url:lla tai /join näkymästä kieltäytyessä kutsusta. Ohjataanko muualtakin, mistä? Footer, tilin luonnin jälkeen jne.?
- Jatkamismahdollisuus näkymästä listaukseen, jos on tultu url:lla, jossa kurssi id?
