### ISSUE TITLE
Sähköpostikoosteessa näkyy kurssin otsikko, vaikka sille ei olisi sisältöä

### ISSUE THREAD

**Issue by nkahe** [Digivertaisverkko/UKK-tiketit#277]
Otsikko näytetään, vaikka kurssilla ei olisi mitään tapahtua.

![Image](https://github.com/Digivertaisverkko/UKK-tiketit-backend/assets/12832691/d28ae00f-1259-459e-8af1-99a51c901278)

Voi käyttäjällä olla epävarmuutta, että onko jotain tapahtumia, mutta niitä ei vain näy.

**Comment by JoniMatias** [comment]
Pitäisi olla korjattu
