### ISSUE TITLE
GDPR-dumpista puuttuu liitteet. (Väärä URL)

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#280]
GDPR-dumppaus lataa tällä hetkellä jsonin osoitteesta /api/minun/gdpr/
mutta oikea osoite, josta löytyy kaikki on  /api/minun/gdpr/kaikki/zip/

**Comment by nkahe** [comment]
näyttää käyttävän oikeaa osoitetta nyt.
