### ISSUE TITLE
Frontille aloitussivu, johon voi LTI:sta ohjata

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#29]
Kun käyttäjä saapuu sivulle LTI:n kautta, backend ohjaa käyttäjän jollekin sivulle, josta frontin pitää osata tulkita seuraavat asiat:
- Kirjautunut käyttäjä (session id)
- Avattavan kurssin tunnus
- Tieto siitä, että nyt ollaan upotetussa iframessa, jolloin käyttöliittymästä voi piilottaa elementtejä
- Kieli

**Comment by nkahe** [comment]
kurssi, session ID ja upotus tunnistetaan nyt listanäkymässä.

**Comment by nkahe** [comment]
Tällä hetkellä kieli otetaan nyt ensisijaisesti URL-parametrista. Jos se on joku muu kuin suomi, niin käytetään englantia. Jos sitä ei ole asetettu eikä olla upotuksessa, niin voi vaihtaa valikosta kuten ennen.
