### ISSUE TITLE
Tiketeille opettaja muokattava kuvaus, jossa opastetaan opiskelijoita täyttämään tikettiä (tai kertomaan mistä on kyse)

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#293]
Eli aina kun opiskelija tekee uuden tiketin, niin tiketinluomisnäkymän yläreunassa näytettäisiin opettajan kirjoittama ohjeistus tiketin täytölle. 

Tähän on ollut tuki tietokannassa jo alusta asti, mutta backedin rajapinta ei ole koskaan palauttanut sitä. Tarvitaanko tätä toiminnallisuutta ollenkaan? Kenttien infonamikat hoitaa pitkälti saman asian?

**Comment by nkahe** [comment]
- [ ] UI-suunn.
- [ ] mockup
- [ ] /submit toteutus
- [ ] /settings toteutus
