### ISSUE TITLE
Tukki-brändäys

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#294]
- [x] Logo heti kun se tulee lopullisessa muodossa.
- [x] Muualle Tukki-nimeä, jos se kuuluu sinne.
- [x] Sähköposti-ilmoituksiin Tukki-nimi.
- [x] Fronttiin Tukki-nimi
- [x] favicon
- [ ] Repojen nimet
- [x] Dokumentaatiossa nimiviittaukset
- [x] Kaikkialla muualla myös (mm. opettajille jaettava materiaali)

**Comment by JoniMatias** [comment]
En äkkiseltään keksi enää paikkoja, jossa tämä brändäys pitäisi tehdä?

Ellei sitten puhuta siitä, pitäisikö githubin repositoriot nimetä uudestaan Tukki-brändin alle?

**Comment by erkkitervoOY** [comment]
Repojen nimiä ei muuteta käytännön syistä. Tehtävä suoritettu.
