### ISSUE TITLE
Aloitussivulle joku kontaktointitieto GDPR-pyyntöjä varten

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#300]
Koska tämä on ainoa sivu, johon käyttäjät pääsevät sen jälkeen kun heiltä on loppunut opinto-oikeus tai edes pääsy kurssialueelle, niin tällä sivulla olisi hyvä olla jonkinlainen yhteydenottomahdollisuus (lomake tai sähköpostiosoite), johon he voisivat laittaa GDPR-poistopyyntönsä.

Tällä hetkellä ainoa GDPR:n poistamiseen liittyvä linkki on "lähetä valitus valvontaviranomaiselle", joka on ongelmallista, jos se on ainoa linkki.

Sähköpostilinkin jakaminen ja siirtäminen ylläpitäjältä toiselle vaatii jonkinlaisen ratkaisun kehittämistä. Mahdollisesti luodaan uusi sähköpostiosoite, jonka on tarkoituskin siirtyä henkilöltä toiselle.

**Comment by nkahe** [comment]
Sähköpostiosoite tuntuisi itsestä tuohon näkymään riittävältä. On varmaan harvemmin käytettävä ominaisuus eikä ruuhkauta tuon näkymän UI:a. Voi tehdä, että osoitetta klikkaamalla aukeaa selaimen määrittelemä meilin lähettäminen.

**Comment by nkahe** [comment]
on nyt linkki tietosuojaselosteeseen ja skrollaus ohjeiden kohtaan (lopussa).

**Comment by nkahe** [comment]
tarvii vielä oikean meiliosoitteen, mihin pyynnöt ohjataan.

**Comment by erkkitervoOY** [comment]
Tietosuojaselosteessa on ohjeet ja yhteystiedot.
