### ISSUE TITLE
Kysymysten lisäohjeeseen ?-vihje?

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#302]
Kysymysten lisäohje on epäselvän oloinen. Tietävätkö käyttäjät mihin kohtaan se sijoittuu, kun sen sijainti vaikuttaa paljon siihen mitä sisältöä siihen kannattaa laittaa.

Voisiko siihen laittaa hiirellä aktivoitavan ?-vihjeen tai leipätekstin, joka kertoo tekstin sijoittuvan viestikentän alapuolelle?

**Comment by nkahe** [comment]
![Image](https://github.com/Digivertaisverkko/UKK-tiketit/assets/12832691/3bc610a7-d71d-4f68-abd9-0603f04a6498)
