### ISSUE TITLE
Kuvauksen haku ja lisäkenttien asettaminen ei toimi kurssilla 2.

### ISSUE THREAD

**Issue by nkahe** [Digivertaisverkko/UKK-tiketit#304]
Tämä on uusimmalla backendillä ja kurssilla 2. kurssilla 1 toimii kuten pitää.

1.	Lähetän kuvauksen.
Tehtiin PUT-pyyntö URL:iin "/api/kurssi/2/tikettipohja/kuvaus". Pyynnön body: "{"kuvaus":"blabla"}". Tilakoodi 200. Saatiin vastaukseksi "{"success":true}". http-interceptor.ts:58:12

2.	Myöhemmin koitan hakea:
Tehtiin GET-pyyntö URL:iin "/api/kurssi/2/tikettipohja/kentat". Tilakoodi 204. Saatiin vastaukseksi "null"

Koitan asettaa lisäkenttiä:
PUT http://localhost:3000/api/kurssi/2/tikettipohja/kentat

Saatin virhe HTTP-tilakoodilla 400 ja viestillä: "Http failure response for http://localhost:3000/api/kurssi/2/tikettipohja/kentat: 400 Bad Request. error.service.ts:109:12
Palvelimen virheen tilakoodi 3000 ja viesti: "Virheelliset parametrit.".

Body:

kentat	[…]
0	{…}
esitaytettava	false
ohje	""
otsikko	"uusi kenttä"
pakollinen	""
valinnat	[]

**Comment by JoniMatias** [comment]
Vika oli sample_datassa.
