### ISSUE TITLE
Avatar näyttää enemmän kuin kaksi alkukirjainta

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#308]
Jos käyttäjän käyttäjänimessä on yli kaksi nimeä, niin silloin Avatar näyttää yli kaksi merkkiä. Ja se ei näytä erityisen kivalta kolmella. ks kuva.

![Image](https://github.com/Digivertaisverkko/UKK-tiketit/assets/1462901/0af10ac2-5b78-4215-8b4a-d7ceb679bbbf)

Olisi ehkä tarkoituksen mukaista, jos siinä näkyisi vain ensimmäinen kirjain, ja viimeisen nimen ensimmäinen kirjain. Ei tästä mitenkään täydellistä saada millään mekanismeillä, joten kokeillaan tuota.

**Comment by nkahe** [comment]
joo tarkoitus oli, että ei huomioi yli kahta sanaa, mutta ei näytä toimivan. 1. ja viimeinen voisi paras.

**Comment by nkahe** [comment]
korjattu
