### ISSUE TITLE
UKK-kysymysten muokkaaminen ja poistaminen

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#33]
Riippuvainen: #34 ja #59 

Koska opettajalla on mahdollisuus lisätä UKK:ita, ja niiden luomisessa voi tapahtua virheitä, joten turhia kysymyksiä on syytä myös poistaa. Myös, kun #32 toteutetaan, niin kurssille voi tulla turhia kysymyksiä, joista opettaja haluaa päästä eroon.

**Comment by nkahe** [comment]
Kysymyksiä voi frontin puolesta nyt muokata.

**Comment by nkahe** [comment]
Toimivat
