### ISSUE TITLE
Tikettilistan nappeja ei voi painaa muualta kuin tekstin kohdalta

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#37]
Tämän voi korjata joko sillä, että koko rivi on painettavissa, tai sitten vain otsikko on painettavissa. Nyt kaikki tekstit ovat painettavissa, ja se ainakin on väärin.

**Comment by nkahe** [comment]
nyt linkin pinta-ala on otsikkokentän sisältö ja hiiren kursorin muutos vastaa sitä
