### ISSUE TITLE
Testataan erilaisilla näytöillä

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#43]

**Comment by nkahe** [comment]
- myös oikealla tabletilla. esim. leiskautuuko oikein virtuaalisella näppäimistöllä.

**Comment by JoniMatias** [comment]
Tällä hetkellä osittain korjattu sillä, että upotuksen voi avata uuteen välilehteen. Tietysti perusleiskakin voi olla rikki pienillä näytöillä.

**Comment by JoniMatias** [comment]
Käytännössä toimii kaikilla ei-mobiililaitteilla.
