### ISSUE TITLE
Tietosuojaselosteen päivitys

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#48]
Tutkimustietoinformointitiedot tietosuojailmoitukseen

**Comment by erkkitervoOY** [comment]
Lisätty kappale 6.5.

Tämä pitää vielä hyväksyttää Helenalta ja pyytää kommentteja myös muilta. Sen jälkeen tämä pitäisi(?) käänää englanniksi.

**Comment by erkkitervoOY** [comment]
Kirjataan kaikki pilkuntarkasti, että miten me käytetään dataa.
