### ISSUE TITLE
Kirjautumisindikaattorin taitto upotusnäkymään

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#63]
Tässä pitänee olla ainakin
- Et ole kirjautunut
  - (Jossa on kirjaudu sisään nappi) <- on virheviestissä
- Olet kirjautunut
  - Kirjautuneen käyttäjän nimi / rooli
  - (Mahdollisuus kirjautua ulos) <- wontfix

**Comment by nkahe** [comment]
- [ ] Suunnitelma toteutuksesta
- [ ] Arkkitehtuurimuutokset
- [ ] Menukomponentti
- [ ] listausnäkymästä toiminnallisuudet pois
- [ ] Vaihtoehtojen näyttäminen eri tilojen mukaan
- [ ] Tooltip
- [ ] Asemointi
