### ISSUE TITLE
Tiketin oletuskenttien ohjeet

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#71]
Tiketeissä on tällä hetkellä kaksi oletuskenttää: tehtävä ja ongelman tyyppi. Me olemme määritelleet, että kaikilla kentillä on kuvaus, joten mitä näihin oletuskenttiin laitetaan kuvauksiksi? Ja miten niiden käännöksen hoidetaan?

Tarviiko ne edes kuvauksia?

**Comment by erkkitervoOY** [comment]
Kuvaus = ohje

Tehty fronttiin tooltipit lisäkenttien viereen, jotka näyttävät kyseiset ohjeet.
