### ISSUE TITLE
Piilota arkistoidut tiketit ja ukk:t

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#78]
Tikettien ja ukk:iden poistaminen arkistoi tiketin. Arkistoituja tikettejä ei pitäisi näkyä opiskelijoilla eikä opettajille.

Niitä varten tarvitaan joskus tulevaisuudessa erillinen näkymä.

**Comment by nkahe** [comment]
Arkistoituja tikettejä ei nyt näytetä.
