### ISSUE TITLE
Kirjoitusvirhe sivun alaotsakkeessa.

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#91]
Alaotsakkeessa olevassa tekstissä on kirjoitusvirhe. Siinä pitäisi lukea:

Tämä on Digivertaisverkkohankkeen tuottama ohjelmisto, joka on kehitetty Oulun Yliopiston ja Oulun Ammattikorkeakoulun yhteistyönä ja Euroopan sosiaalirahaston rahoittamana.

Sama ja-sana puuttuu myös englanninkielisestä versiosta:

This is software produced by the Diginet project, developed in cooperation between the University of Oulu and Oulu University of Applied Sciences and funded by the European Social Fund.

Tai ehkä vielä parempi muotoilu olisi:

Tämä on Digivertaisverkkohankkeen tuottama ohjelmisto. Digivertaisverkko on Euroopan sosiaalirahaston rahoittama hanke, joka on toteutettu Oulun Yliopiston ja Oulun Ammattikorkeakoulun yhteistyönä.

**Comment by nkahe** [comment]
laitoin jälkimmäisen ja käännöksen ehdolle
