### ISSUE TITLE
Tikettien luotu-kentän muotoilu ei noudata localea, ja se on aina muotoiltu jenkkiläiseksi.

### ISSUE THREAD

**Issue by JoniMatias** [Digivertaisverkko/UKK-tiketit#97]
![Image](https://user-images.githubusercontent.com/1462901/216619970-8fa902a1-6f17-49f1-a479-89740bcf55c3.png)

**Comment by nkahe** [comment]
Ainakin näillä toistaiseksi vaikuttaa nyt toimivan.
